version: "3"
services:

    db:
        image: mysql:8.0.15
        command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--default-authentication-plugin=mysql_native_password']
        ports:
            - "3307:3307"
        environment:
            MYSQL_DATABASE: dockerProjet
            MYSQL_USER: userdb
            MYSQL_PASSWORD: userdb
            MYSQL_ROOT_PASSWORD: userdb
        volumes:
            - ./sql:/docker-entrypoint-initdb.d
            - stock:/var/lib/mysql
        networks:
            - default

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:4.8
        links:
            - db:db
        ports:
            - 8002:80
        environment:
            MYSQL_USER: userdb
            MYSQL_PASSWORD: userdb
            MYSQL_ROOT_PASSWORD: userdb

    web:
        build: .
        ports:
            - "8001:80"
        volumes:
            - ./website:/var/www/html/
        links:
            - db
        networks:
            - default

volumes:
    stock:
